<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_SelectAfghanAlbanianAlgeria</name>
   <tag></tag>
   <elementGuidId>4242ecdd-2230-4c5e-b633-d2340bbf38bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select2-skp9-results']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__options</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tree</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-skp9-results</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectAfghanAlbanianAlgerianAmerican SamoanAndorranAngolanAnguillanAntiguan or BarbudanArgentineArmenianArubanAustralianAustrianAzerbaijaniBahamianBahrainiBangladeshiBarbadianBelarusianBelgianBelizeanBenineseBermudianBhutaneseBolivianBosnian or HerzegovinianBotswananBrazilianBruneianBulgarianBurkinabéBurundianCambodianCameroonianCanadianCape VerdeCaymanianCentral AfricanChadianChileanChineseChristmas IslandCocos IslandColombianComorianCongoleseCongoleseCook IslandCosta RicanIvorianCroatianCubanCypriotCzechDanishDjiboutianDominicanDominicanEcuadorianEgyptianSalvadoranEquatoguineanEritreanEstonianEthiopianFalkland IslandFaroeseFijianFinnishFrenchFrench GuianeseFrench PolynesianGaboneseGambianGeorgianGermanGhanaianGibraltarHellenicGreenlandicGrenadianGuadeloupeGuamanianGuatemalanGuineanBissau-GuineanGuyaneseHaitianHonduranHong KongeseHungarianIcelandicIndianIndonesianIranianIraqiIrishIsraeliItalianJamaicanJapaneseJordanianKazakhstaniKenyanI-KiribatiNorth KoreanSouth KoreanKuwaitiKyrgyzstaniLaotianLatvianLebaneseBasothoLiberianLibyanLiechtensteinLithuanianLuxembourgishMacaneseMacedonianMalagasyMalawianMalaysianMaldivianMalianMalteseMARSHALL ISLANDSMartinicanMauritanianMauritianMahoranMexicanMicronesianMoldovanMonacanMongolianMontserratianMoroccanMozambicanBurmeseNamibianNauruanNepaliDutchNew CaledonianNew ZealandNicaraguanNigerianNigerianNiueanNorfolk IslandNorthern MariananNorwegianOmaniPakistaniPalauanPalestinianPanamanianPapuanParaguayanPeruvianFilipinoPolishPortuguesePuerto RicanQatariReunioneseRomanianRussianRwandanSaint HelenianKittitianSaint LucianSaint-PierraisSaint VincentianSamoanSammarineseSao TomeanSaudi ArabianSenegaleseSerbianSeychelloisSierra LeoneanSingaporeanSlovakSlovenianSolomon IslandSomalianSouth AfricanSpanishSri LankanSudaneseSurinameseSvalbardSwaziSwedishSwissSyrianTaiwaneseTajikistaniTanzanianThaiTimoreseTogoleseTokelauanTonganTrinidadianTunisianTurkishTurkmenTurks and Caicos IslandTuvaluanUgandanUkrainianEmiratiBritishAmericanUruguayanUzbekistaniVanuatuanVenezuelanVietnameseWallis and FutunaSahrawiYemeniZambianZimbabwean</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-skp9-results&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//ul[@id='select2-skp9-results']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'select2-skp9-results', '&quot;', ')')])[1]/following::ul[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::ul[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//span[2]/ul</value>
   </webElementXpaths>
</WebElementEntity>
