<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpdev-chiragh.surge.shauth</name>
   <tag></tag>
   <elementGuidId>f20f9ceb-8ef7-4da1-9c44-48e6fb062bc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;:om&quot;]/span/a[count(. | //a[@href = 'http://dev-chiragh.surge.sh/auth/resetPassword/a8615f4b219d18b4a1f1f12ca738d6af' and (text() = 'http://dev-chiragh.surge.sh/auth/resetPassword/a8615f4b219d18b4a1f1f12ca738d6af' or . = 'http://dev-chiragh.surge.sh/auth/resetPassword/a8615f4b219d18b4a1f1f12ca738d6af')]) = count(//a[@href = 'http://dev-chiragh.surge.sh/auth/resetPassword/a8615f4b219d18b4a1f1f12ca738d6af' and (text() = 'http://dev-chiragh.surge.sh/auth/resetPassword/a8615f4b219d18b4a1f1f12ca738d6af' or . = 'http://dev-chiragh.surge.sh/auth/resetPassword/a8615f4b219d18b4a1f1f12ca738d6af')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':ny']/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://dev-chiragh.surge.sh/auth/resetPassword/a8615f4b219d18b4a1f1f12ca738d6af</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?q=http://dev-chiragh.surge.sh/auth/resetPassword/a8615f4b219d18b4a1f1f12ca738d6af&amp;source=gmail&amp;ust=1547714621250000&amp;usg=AFQjCNHsy1zqdhd82n2m_yIYXmghU3AQ1g</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>http://dev-chiragh.surge.sh/auth/resetPassword/a8615f4b219d18b4a1f1f12ca738d6af</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;:om&quot;]/span/a</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id=':ny']/span/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fatimazaidi1995+03'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forward'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <value>//a[@href='http://dev-chiragh.surge.sh/auth/resetPassword/a8615f4b219d18b4a1f1f12ca738d6af']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[3]/div/span/a</value>
   </webElementXpaths>
</WebElementEntity>
